# Конфигурация UraniumCraft

# Настройки радиации
radiation:
  # Естественное снижение радиации (единиц в минуту)
  natural_decay: 2
  
  # Максимальный уровень радиации
  max_level: 100
  
  # Эффективность защитного костюма (0.0 - 1.0)
  hazmat_protection: 0.75
  
  # Радиация от добычи урановой руды
  mining_radiation: 5
  
  # Радиация от работы с центрифугой
  centrifuge_radiation: 10

# Настройки лабораторий
laboratory:
  # Максимальное количество лабораторий на игрока
  max_per_player: 2
  
  # Время строительства лаборатории (секунды)
  construction_time: 300
  
  # Базовая генерация энергии
  base_energy_generation: 10
  
  # Автоматическое сохранение прогресса (секунды)
  auto_save_interval: 60

# Настройки центрифуги
centrifuge:
  # Время обработки материалов (секунды)
  processing_time: 180
  
  # Множитель выхода материалов
  output_multiplier: 1.5
  
  # Шанс получения редких материалов (0.0 - 1.0)
  rare_material_chance: 0.1
  
  # Максимальное количество центрифуг на игрока
  max_per_player: 3

# Настройки исследований
research:
  # Базовая скорость исследований
  base_speed: 1.0
  
  # Энергия за тик исследования
  energy_per_tick: 5

# Настройки достижений
achievements:
  # Включить систему достижений
  enabled: true
  
  # Показывать уведомления всем игрокам
  broadcast_notifications: false

# Сообщения плагина
messages:
  prefix: "&8[&eUraniumCraft&8]&r "
  no_permission: "&cУ вас нет прав для выполнения этой команды!"
  player_not_found: "&cИгрок не найден!"
  invalid_usage: "&cНеправильное использование команды!"
  
  radiation:
    level_safe: "&aБезопасный уровень"
    level_moderate: "&eУмеренный уровень"
    level_elevated: "&6Повышенный уровень"
    level_high: "&cВысокий уровень"
    level_critical: "&4КРИТИЧЕСКИЙ УРОВЕНЬ"
