name: UraniumCraft
version: 2.0.0
main: com.uraniumcraft.UraniumPlugin
api-version: 1.21
author: UraniumCraft Team
description: Урановый плагин с радиацией, лабораториями и высокотехнологичным оборудованием

commands:
  uranium:
    description: Главная команда плагина
    usage: /uranium [подкоманда]
    permission: uraniumcraft.use
  laboratory:
    description: Команды лаборатории
    usage: /laboratory [подкоманда]
    permission: uraniumcraft.laboratory.use
  teleporter:
    description: Команды телепорта (админ)
    usage: /teleporter [подкоманда]
    permission: uraniumcraft.teleporter.admin
  tablet:
    description: Команды планшета
    usage: /tablet [подкоманда]
    permission: uraniumcraft.tablet.use
  tp:
    description: Меню телепортации
    usage: /tp
    permission: uraniumcraft.teleporter.use

permissions:
  uraniumcraft.*:
    description: Все права плагина
    children:
      uraniumcraft.use: true
      uraniumcraft.admin: true
      uraniumcraft.laboratory.*: true
      uraniumcraft.teleporter.*: true
      uraniumcraft.tablet.*: true
  
  uraniumcraft.use:
    description: Базовое использование плагина
    default: true
  
  uraniumcraft.admin:
    description: Административные права
    default: op
  
  uraniumcraft.laboratory.*:
    description: Все права лаборатории
    children:
      uraniumcraft.laboratory.use: true
      uraniumcraft.laboratory.create: true
  
  uraniumcraft.laboratory.use:
    description: Использование лаборатории
    default: true
  
  uraniumcraft.laboratory.create:
    description: Создание лаборатории
    default: true
  
  uraniumcraft.teleporter.*:
    description: Все права телепорта
    children:
      uraniumcraft.teleporter.use: true
      uraniumcraft.teleporter.admin: true
  
  uraniumcraft.teleporter.use:
    description: Использование телепорта
    default: true
  
  uraniumcraft.teleporter.admin:
    description: Администрирование телепортов
    default: op
  
  uraniumcraft.tablet.*:
    description: Все права планшета
    children:
      uraniumcraft.tablet.use: true
      uraniumcraft.tablet.give: true
  
  uraniumcraft.tablet.use:
    description: Использование планшета
    default: true
  
  uraniumcraft.tablet.give:
    description: Выдача планшетов
    default: op
